
package com.roma.elettorale.fascicoli.entity.certi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Holder;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ComuneCertificatiBinding", targetNamespace = "http://www.comune.roma.it/certificati")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ComuneCertificatiBinding {


    /**
     * 
     * @param idClient
     * @param codiceFiscale
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "http://www.comune.roma.it/certificati/ricercaPersona")
    @WebResult(name = "persona", targetNamespace = "")
    @RequestWrapper(localName = "ricercaPersona", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RicercaPersona")
    @ResponseWrapper(localName = "ricercaPersonaResponse", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RicercaPersonaResponse")
    public String ricercaPersona(
        @WebParam(name = "idClient", targetNamespace = "")
        int idClient,
        @WebParam(name = "codiceFiscale", targetNamespace = "")
        String codiceFiscale);

    /**
     * 
     * @param idClient
     * @param codiceFiscaleRichiedente
     * @return
     *     returns com.roma.elettorale.fascicoli.entity.certi.ArrayOfComponenteFamigliaType
     */
    @WebMethod(action = "http://www.comune.roma.it/certificati/ricercaComponentiFamiglia")
    @WebResult(name = "componentiFamiglia", targetNamespace = "")
    @RequestWrapper(localName = "ricercaComponentiFamiglia", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RicercaComponentiFamiglia")
    @ResponseWrapper(localName = "ricercaComponentiFamigliaResponse", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RicercaComponentiFamigliaResponse")
    public ArrayOfComponenteFamigliaType ricercaComponentiFamiglia(
        @WebParam(name = "idClient", targetNamespace = "")
        int idClient,
        @WebParam(name = "codiceFiscaleRichiedente", targetNamespace = "")
        String codiceFiscaleRichiedente);

    /**
     * 
     * @param idClient
     * @param codiceFiscale
     * @param ciu
     * @return
     *     returns com.roma.elettorale.fascicoli.entity.certi.ArrayOfBase64Binary
     */
    @WebMethod(action = "http://www.comune.roma.it/certificati/recuperaDocumento")
    @WebResult(name = "recuperaDocumentoResult", targetNamespace = "http://www.comune.roma.it/certificati/data")
    @RequestWrapper(localName = "recuperaDocumento", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RecuperaDocumento")
    @ResponseWrapper(localName = "recuperaDocumentoResponse", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RecuperaDocumentoResponse")
    public ArrayOfBase64Binary recuperaDocumento(
        @WebParam(name = "idClient", targetNamespace = "")
        int idClient,
        @WebParam(name = "codiceFiscale", targetNamespace = "")
        String codiceFiscale,
        @WebParam(name = "CIU", targetNamespace = "")
        String ciu);

    /**
     * 
     * @param intestatarioTrovato
     * @param credenziali
     * @param transactionRequest
     */
    @WebMethod(action = "http://www.comune.roma.it/certificati/richiestaCredenziali")
    @RequestWrapper(localName = "richiestaCredenziali", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RichiestaCredenziali")
    @ResponseWrapper(localName = "richiestaCredenzialiResponse", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RichiestaCredenzialiResponse")
    public void richiestaCredenziali(
        @WebParam(name = "transactionRequest", targetNamespace = "")
        TransactionRequestType transactionRequest,
        @WebParam(name = "credenziali", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<CredenzialiType> credenziali,
        @WebParam(name = "intestatarioTrovato", targetNamespace = "", mode = WebParam.Mode.OUT)
        Holder<Boolean> intestatarioTrovato);

    /**
     * 
     * @param certificati
     * @param credenziali
     */
    @WebMethod(action = "http://www.comune.roma.it/certificati/verificaEmettibilita")
    @RequestWrapper(localName = "verificaEmettibilita", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.VerificaEmettibilita")
    @ResponseWrapper(localName = "verificaEmettibilitaResponse", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.VerificaEmettibilitaResponse")
    public void verificaEmettibilita(
        @WebParam(name = "credenziali", targetNamespace = "")
        CredenzialiType credenziali,
        @WebParam(name = "certificati", targetNamespace = "", mode = WebParam.Mode.INOUT)
        Holder<ArrayOfInfoCertificatoType> certificati);

    /**
     * 
     * @param certificati
     * @param credenziali
     * @return
     *     returns com.roma.elettorale.fascicoli.entity.certi.ArrayOfCertificatoType
     */
    @WebMethod(action = "http://www.comune.roma.it/certificati/richiestaCertificati")
    @WebResult(name = "certificati", targetNamespace = "")
    @RequestWrapper(localName = "richiestaCertificati", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RichiestaCertificati")
    @ResponseWrapper(localName = "richiestaCertificatiResponse", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.RichiestaCertificatiResponse")
    public ArrayOfCertificatoType richiestaCertificati(
        @WebParam(name = "credenziali", targetNamespace = "")
        CredenzialiType credenziali,
        @WebParam(name = "certificati", targetNamespace = "")
        ArrayOfInfoCertificatoType certificati);

    /**
     * 
     * @param certificati
     * @param credenziali
     * @return
     *     returns boolean
     */
    @WebMethod(action = "http://www.comune.roma.it/certificati/confermaStampa")
    @WebResult(name = "esitoConferma", targetNamespace = "")
    @RequestWrapper(localName = "confermaStampa", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.ConfermaStampa")
    @ResponseWrapper(localName = "confermaStampaResponse", targetNamespace = "http://www.comune.roma.it/certificati/data", className = "com.roma.elettorale.fascicoli.entity.certi.ConfermaStampaResponse")
    public boolean confermaStampa(
        @WebParam(name = "credenziali", targetNamespace = "")
        CredenzialiType credenziali,
        @WebParam(name = "certificati", targetNamespace = "")
        ArrayOfString certificati);

}
